name: Build Macroquad APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Platform 29
        run: |
          yes | sdkmanager "platforms;android-29"

      - name: Install cargo-quad-apk
        run: cargo install cargo-quad-apk
        
      # حذف فایل lock ناسازگار برای ساخت خودکار توسط کارگو
      - name: Remove incompatible Cargo.lock
        run: rm -f Cargo.lock
        
      - name: Build APK
        env:
          NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: cargo quad-apk build --release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/android/release/apk/*.apk